
import localFont from "next/font/local";
import "./globals.css";
import { Web3ContextProvider } from "@/context/Web3Context";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { Urbanist } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
const urbanist = Urbanist({ subsets: ["latin"] });


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={urbanist.className}
      >
        <AntdRegistry>
          <Web3ContextProvider>
            {children}
          </Web3ContextProvider>

        </AntdRegistry>
      </body>
    </html>
  );
}
